/**
 * Static data adapter — replaces the live backend API.
 * Reads pre-exported JSON from /data/ (generated by export_db_to_json.py).
 * Write operations (start/stop/refresh) are no-ops.
 */

const staticGet = async (url) => {
  // GET /api/v1/history/teams
  if (url === "/api/v1/history/teams") {
    const res = await fetch("/data/teams.json");
    return { data: await res.json(), status: 200 };
  }

  // GET /api/v1/history/analytics/{team_name}
  const analyticsMatch = url.match(/\/api\/v1\/history\/analytics\/(.+)/);
  if (analyticsMatch) {
    const teamName = decodeURIComponent(analyticsMatch[1]);
    const res = await fetch(`/data/analytics/${teamName}.json`);
    if (!res.ok) {
      throw { response: { data: { message: `No data for team '${teamName}'` } }, message: "Not found" };
    }
    // Backend returns an array with one element
    return { data: [await res.json()], status: 200 };
  }

  // GET /api/v1/collect/event-status
  if (url === "/api/v1/collect/event-status") {
    const res = await fetch("/data/event-status.json");
    return { data: await res.json(), status: 200 };
  }

  console.warn("[static mode] Unhandled GET:", url);
  return { data: {}, status: 200 };
};

const staticPost = async (url) => {
  // All write operations are no-ops in static mode
  console.warn("[static mode] POST ignored (no backend):", url);
  return {
    data: { success: true, message: "Static mode — no backend available", status: "idle" },
    status: 200,
  };
};

const commitAnalyzerClient = {
  get: staticGet,
  post: staticPost,
  patch: staticPost,
  delete: staticPost,
};

export default commitAnalyzerClient;
